"""Stable rule-baseline signal taxonomy.

The names here are intentionally reviewer-readable and stable. They are
research triage signals, not legal findings.
"""

from __future__ import annotations

from .types import SignalDefinition


TEXTUAL_LURE = "textual_lure"
REDIRECT_CONTACT = "redirect_contact"
URGENCY_PRESSURE = "urgency_pressure"
TESTIMONIAL_SCREENSHOT = "testimonial_screenshot"
PSEUDO_OFFICIAL_ENDORSEMENT = "pseudo_official_endorsement"
PAYMENT_CREDENTIAL = "payment_credential"
OCR_CONTEXT = "ocr_context"
REPLY_FUNNEL = "reply_funnel"


SIGNAL_DEFINITIONS: dict[str, SignalDefinition] = {
    "GUARANTEED_PROFIT": SignalDefinition(
        signal_code="GUARANTEED_PROFIT",
        reason_code="GUARANTEED_PROFIT",
        category=TEXTUAL_LURE,
        description="Guaranteed, risk-free, fixed-return, or no-loss claim.",
        default_weight=4.0,
        patterns=(
            r"\bguaranteed (daily )?(profit|return|income|payout)\b",
            r"\brisk[- ]?free\b",
            r"\bno loss(es)?\b",
            r"\bfixed roi\b",
            r"\bdaily profit\b",
            r"\bguaranteed\b",
            r"\balways go(es)? up\b",
            r"\bstrong upside\b",
            r"會一直漲",
            r"目標價",
        ),
    ),
    "LOW_EFFORT_HIGH_RETURN": SignalDefinition(
        signal_code="LOW_EFFORT_HIGH_RETURN",
        reason_code="LOW_EFFORT_HIGH_RETURN",
        category=TEXTUAL_LURE,
        description="Low-effort or unusually large benefit claim.",
        default_weight=5.0,
        patterns=(
            r"\bturn\s+\$?\d+[\d,]*\s+into\s+\$?\d+[\d,]*\b",
            r"\b\d+%\s+(a|per|each)?\s*(day|week|month)\b",
            r"\b(passive|easy)\s+income\b",
            r"\beasy money\b",
            r"\bmake\s+\$?\d+[\d,]*\b",
            r"\bhigh return\b",
            r"\bcopy and earn\b",
            r"\btarget[- ]?price\b",
            r"\bstock[- ]?pick\b",
        ),
    ),
    "PAST_PERFORMANCE_PROFIT_PROOF": SignalDefinition(
        signal_code="PAST_PERFORMANCE_PROFIT_PROOF",
        reason_code="PAST_PERFORMANCE_PROFIT_PROOF",
        category=TEXTUAL_LURE,
        description="Past stock-pick performance, hit-rate, limit-up, profit table, or wealth-result proof.",
        default_weight=4.0,
        patterns=(
            r"\bmy (pick|recommendation|call)s? (was|were|hit|right)\b",
            r"\bpast performance\b",
            r"\bprofit table\b",
            r"\bhit[- ]?rate\b",
            r"\blimit[- ]?up\b",
            r"\bfinancially free\b",
            r"\b(prediction|predictions) (was|were|are)? ?accurate\b",
            r"\bmarket[- ]timing\b",
            r"\bcalls in advance\b",
            r"我的推薦.{0,8}(沒錯|很準|準)",
            r"(真的|強勢)?漲停",
            r"真的漲了",
            r"跟上.{0,12}(豪宅|財富自由|賺|獲利)",
            r"報.{0,6}(準|這麼準)",
            r"財富自由",
            r"純粹.{0,8}(分享|交朋友)",
        ),
    ),
    "HIGH_FEE_COURSE_FUNNEL": SignalDefinition(
        signal_code="HIGH_FEE_COURSE_FUNNEL",
        reason_code="HIGH_FEE_COURSE_FUNNEL",
        category=TEXTUAL_LURE,
        description="High-fee course, academy, membership, coaching, or trading-education funnel.",
        default_weight=2.5,
        patterns=(
            r"\b(high[- ]?ticket|paid)\s+(course|coaching|academy|membership)\b",
            r"\bhigh[- ]?(fee|price)\s+(course|coaching|academy|membership)\b",
            r"\b(course|coaching|academy|membership)\s+(fee|price)s?\b",
            r"\btrading\s+(course|academy|coaching|school|membership)\b",
            r"(\d+\s*)?萬.{0,8}(課程|學費|費用|收費|報名|入會|會員)",
            r"(課程|學院|教學|導師|會員|社群).{0,12}(交易|投資|股票|外匯|加密貨幣|獲利)",
            r"(交易|投資|股票|外匯|加密貨幣|獲利).{0,12}(課程|學院|教學|導師|會員|社群)",
        ),
    ),
    "STOCK_RESCUE_GROUP_FUNNEL": SignalDefinition(
        signal_code="STOCK_RESCUE_GROUP_FUNNEL",
        reason_code="STOCK_RESCUE_GROUP_FUNNEL",
        category=TEXTUAL_LURE,
        description="Trapped-stock rescue, synchronized operation, free stock community, or stock-help group funnel.",
        default_weight=4.0,
        patterns=(
            r"\bstock[- ]?(rescue|help|community|group)\b",
            r"\bsynchronized (operation|trading)\b",
            r"\bfree stock (help|community|group|analysis)\b",
            r"(套牢|解套).{0,16}(股票|個股|持股|問我|參考)",
            r"(同步操作|跟我同步|跟單|社團|社群|圈子).{0,16}(股票|個股|操作|學習|免費)",
            r"(股票|個股|持股).{0,16}(賴上|LINE|私信|私訊|社團|社群|圈子)",
            r"(社群|社團).{0,12}(開放|連結|學習|免費)",
            r"\b(joined|join(ed)? the) group\b",
            r"\bawaiting approval\b",
        ),
    ),
    "INDIVIDUAL_STOCK_ADVICE_REPLY_FUNNEL": SignalDefinition(
        signal_code="INDIVIDUAL_STOCK_ADVICE_REPLY_FUNNEL",
        reason_code="INDIVIDUAL_STOCK_ADVICE_REPLY_FUNNEL",
        category=TEXTUAL_LURE,
        description="Repeated individualized stock buy, hold, add, wait, sell, or target guidance in replies.",
        default_weight=3.0,
        patterns=(
            r"\b(can|should) (i|we) (buy|add|hold|sell)\b",
            r"\b(add|hold|wait|sell|buy) (more|it|shares?)\b",
            r"\btarget price\b",
            r"\bspecific stocks\b",
            r"\bindividualized directional answers\b",
            r"\b(buy|add|hold|wait|sell)/(add|hold|wait|sell)\b",
            r"\bbought, added, held, or waited\b",
            r"(可以|能不能|還可|怎麼看|如何處理).{0,18}(買|進|加碼|抱|放著|等|賣|上去)",
            r"(買|進|加碼|抱|放著|等|賣|不看好|可以啊|會啊|是的)",
            r"(手上|持有|一張|成本|套牢).{0,18}(如何處理|怎麼看|買|賣|抱|等)",
            r"(已加群組|待審核|加群|群組)",
        ),
    ),
    "MARKET_DIRECTION_HERDING_CHORUS": SignalDefinition(
        signal_code="MARKET_DIRECTION_HERDING_CHORUS",
        reason_code="MARKET_DIRECTION_HERDING_CHORUS",
        category=TEXTUAL_LURE,
        description="Strong market-direction call amplified by buy/add/hold/refill/following chorus.",
        default_weight=4.0,
        patterns=(
            r"\b(full[- ]?position|all[- ]?in|buy[- ]?the[- ]?dip|hold|add|refill)\b",
            r"\bignore (bearish|short|negative) (voices|comments)\b",
            r"\bfollower chorus\b",
            r"\bmarket[- ]direction call\b",
            r"(滿水位|沒有調節|仍然看多|還是做多|不要被.{0,8}影響)",
            r"(加碼|補貨|買了|抱著|簽\\+|衝衝衝|gogogo|噴噴噴)",
            r"(補貨日|補貨的好日子|購物日)",
        ),
    ),
    "INSTITUTIONAL_FLOW_AUTHORITY_LURE": SignalDefinition(
        signal_code="INSTITUTIONAL_FLOW_AUTHORITY_LURE",
        reason_code="INSTITUTIONAL_FLOW_AUTHORITY_LURE",
        category=TEXTUAL_LURE,
        description="Institutional flow, macro event, or foreign-investor data used as authority for a strong trading action.",
        default_weight=3.5,
        patterns=(
            r"\binstitutional (flow|buying|investors?)\b",
            r"\binstitutional/foreign[- ]?investor/futures/spot[- ]?flow\b",
            r"\bforeign (investor|fund|capital|buying)\b",
            r"\bforeign[- ]?investor\b",
            r"\bfutures/spot\b",
            r"\bmacro/weekend[- ]?risk\b",
            r"\bmacro (event|risk|signal)\b",
            r"\bstrongly (long|bullish|buy)\b",
            r"(外資|法人|期現貨|空單|現貨).{0,20}(做多|大買|回補|狂補|買超)",
            r"(戰爭|週末|行情|利多|利空).{0,24}(安心|做多|不要怕|強力做多)",
            r"(期貨|現貨).{0,18}(大幅做多|狂做多|空單狂補|大買)",
            r"(安心.{0,8}(過週末|做多)|跟我做多|強力做多)",
        ),
    ),
    "LIFESTYLE_TRUST_MARKET_REASSURANCE_FUNNEL": SignalDefinition(
        signal_code="LIFESTYLE_TRUST_MARKET_REASSURANCE_FUNNEL",
        reason_code="LIFESTYLE_TRUST_MARKET_REASSURANCE_FUNNEL",
        category=TEXTUAL_LURE,
        description="Lifestyle or parasocial trust framing paired with market reassurance and buy/hold/add guidance.",
        default_weight=3.0,
        patterns=(
            r"\blifestyle trust\b",
            r"\blifestyle/travel warmth\b",
            r"\bmarket reassurance funnel\b",
            r"\bparasocial trust\b",
            r"\bmarket fear reassurance\b",
            r"\bmarket panic interpretation\b",
            r"\bbuy/hold/add/low[- ]?buy guidance\b",
            r"(美景|旅行|夜景|早安|晚安|溫暖|生活).{0,40}(安心|強心針|市場|台股|持股)",
            r"(恐慌|賣壓|多殺多|震盪|開低|見綠).{0,40}(安心|好好抱|逢低|買入|勤撿|持加)",
            r"(劇本|故事).{0,24}(寫好|放著|演完|參考)",
            r"(見綠就買|逢低再買|好好抱著|勤撿持加|入袋為安)",
        ),
    ),
    "DARK_HORSE_STOCK_TARGET_PRICE_DM_FUNNEL": SignalDefinition(
        signal_code="DARK_HORSE_STOCK_TARGET_PRICE_DM_FUNNEL",
        reason_code="DARK_HORSE_STOCK_TARGET_PRICE_DM_FUNNEL",
        category=REDIRECT_CONTACT,
        description="Hidden or dark-horse stock target-price lure gated behind follow, message, code, or private sharing action.",
        default_weight=4.0,
        patterns=(
            r"\bdark[- ]?horse stock\b",
            r"\bhidden (ticker|stock|pick)\b",
            r"\btarget[- ]?price\b",
            r"\bmust[- ]?buy\b",
            r"\bmajor[- ]?brand catalyst\b",
            r"\bfollow.{0,24}message.{0,24}(code|free|share|entry)\b",
            r"(黑馬股|黑馬.{0,6}股|必買黑馬|隱藏標的|代碼遮蔽|\*\*\d?\*)",
            r"(現價|目前價格|低價).{0,16}(最高|目標|預計).{0,12}(價|價格)",
            r"(錯過|別錯過).{0,12}(半年|等|機會)",
            r"(小資族|小資).{0,12}(進場|可進場)",
            r"(突破|技術|簽約|共同研發|重大合作|大廠).{0,24}(題材|利多|合作|模組|封裝|AI|半導體)",
            r"(按讚|追蹤|傳訊|私訊).{0,16}(暗號|代碼|數字|免費|分享|上車|資料)",
            r"(資料已經整理好|資料整理好).{0,16}(追蹤|傳訊|私訊|傳你|傳妳)",
        ),
    ),
    "CODED_ANIMAL_STOCK_LIMIT_UP_GROUP_FUNNEL": SignalDefinition(
        signal_code="CODED_ANIMAL_STOCK_LIMIT_UP_GROUP_FUNNEL",
        reason_code="CODED_ANIMAL_STOCK_LIMIT_UP_GROUP_FUNNEL",
        category=REDIRECT_CONTACT,
        description="Animal-coded or obscured low-price stock lure with near-term limit-up/exit claim and group or DM gate.",
        default_weight=4.0,
        patterns=(
            r"\banimal[- ]?coded stock\b",
            r"\bobscured low[- ]?price stock\b",
            r"\bnear[- ]?term limit[- ]?up\b",
            r"\bgroup.{0,16}(dm|message|join|plus one|\\+1)\b",
            r"(金豬|養成.{0,6}金豬|本週.{0,8}金豬)",
            r"(低價標|低價.{0,6}標).{0,18}(漲停|下車|免費|分享)",
            r"(兩三天|2-3天|二三天).{0,16}(漲停|下車)",
            r"(資料準備好|資料已經整理好|資料準備好了).{0,18}(群組|追蹤|傳訊|私訊|\\+1)",
            r"(加入群組|還沒加入群組).{0,18}(追蹤|傳訊|私訊|\\+1|即可)",
            r"(追蹤|傳訊|私訊).{0,12}(\\+1|群組|資料|免費分享)",
        ),
    ),
    "MASS_STOCK_COMMAND_LIST_GROUP_FUNNEL": SignalDefinition(
        signal_code="MASS_STOCK_COMMAND_LIST_GROUP_FUNNEL",
        reason_code="MASS_STOCK_COMMAND_LIST_GROUP_FUNNEL",
        category=REDIRECT_CONTACT,
        description="Mass stock buy/sell/limit-up command list that converts readers into a daily stock-signal group or quota.",
        default_weight=4.0,
        patterns=(
            r"\bmass stock command list\b",
            r"\bdaily stock[- ]?signal group\b",
            r"\bfree daily stock picks?\b",
            r"\bbuy/sell command list\b",
            r"\baccurate stock calls?\b",
            r"(報牌|喊單).{0,10}(準|精準|免費|每日)",
            r"(下週|明天|週一).{0,16}(建議|買|上車|下車)",
            r"(快上車|快下車|上車名額|領取上車)",
            r"(會持續漲|會漲停|漲停).{0,18}(上車|報牌|分享|群組)?",
            r"(群組|社群).{0,16}(每日|精準|報牌|進出時機|技術分析|免費分享)",
            r"(按讚|追蹤|留言|回覆).{0,12}(\\+1|領取|名額|上車|群組|免費)",
            r"(進出時機|技術分析).{0,16}(免費|分享|群組|每日)",
        ),
    ),
    "TRADING_RULES_WEALTH_AUTHORITY_FOLLOW_GATE": SignalDefinition(
        signal_code="TRADING_RULES_WEALTH_AUTHORITY_FOLLOW_GATE",
        reason_code="TRADING_RULES_WEALTH_AUTHORITY_FOLLOW_GATE",
        category=REDIRECT_CONTACT,
        description="Trading-rule list and wealth/experience authority lure gated behind like, follow, +1, or get-on-board action.",
        default_weight=4.0,
        patterns=(
            r"\btrading[- ]?rules wealth authority\b",
            r"\bwealth authority follow gate\b",
            r"\bget[- ]?on[- ]?board\b",
            r"(炒股|股票|台股).{0,18}(年|資產|身家|財富).{0,24}(規則|守這|口訣|紀律)",
            r"(資產|身家|財富).{0,16}(萬|億).{0,36}(按讚|追蹤|關注|\\+1|上車)",
            r"(守這|只守|紀律|規則).{0,40}(按讚|追蹤|關注|\\+1|上車)",
            r"(買哪一|怎麼買|何時買|判斷).{0,28}(按讚|追蹤|關注|\\+1|上車|帶你)",
            r"(按讚|追蹤|關注).{0,12}(\\+1|上車|帶你|買股票|股票)",
        ),
    ),
    "BRAND_PATENT_EXTREME_ROI_CONTACT_FUNNEL": SignalDefinition(
        signal_code="BRAND_PATENT_EXTREME_ROI_CONTACT_FUNNEL",
        reason_code="BRAND_PATENT_EXTREME_ROI_CONTACT_FUNNEL",
        category=REDIRECT_CONTACT,
        description="Brand/patent/catalyst authority plus extreme ROI lure and contact or private-message gate.",
        default_weight=5.0,
        patterns=(
            r"\bbrand patent extreme roi\b",
            r"\bexclusive patent.{0,24}(contact|dm|message|line|private)\b",
            r"\bsmall stake.{0,24}(huge return|extreme roi)\b",
            r"(獨家專利|指定.{0,8}專利|晶片封裝|冷卻液).{0,40}(目標價|四位數|直衝|波段空間|免費領取|私訊|賴)",
            r"(訂單排到|全面導入|達成簽約|大廠).{0,40}(目標價|四位數|直衝|波段空間|免費領取|私訊|賴)",
            r"(準備|投入|本金).{0,12}(新台幣|元|塊).{0,24}(萬|倍|%|波段空間)",
            r"(現價|目前價格|僅|才).{0,14}(預計最高價|最高價|目標價|四位數|直衝)",
            r"(追蹤|按讚|私敲|私訊|賴上|賴id|line).{0,18}(免費領取|參考|明日入場|\\+1)",
        ),
    ),
    "BEGINNER_EASY_MONEY": SignalDefinition(
        signal_code="BEGINNER_EASY_MONEY",
        reason_code="BEGINNER_EASY_MONEY",
        category=TEXTUAL_LURE,
        description="Beginner, no-experience, or anyone-can-earn framing.",
        default_weight=2.0,
        patterns=(
            r"\bbeginners? can (earn|make|start)\b",
            r"\bno experience (needed|required)\b",
            r"\banyone can (earn|make|join)\b",
            r"\bstart earning today\b",
            r"\bwork from home\b",
        ),
    ),
    "MENTOR_COPYTRADE_LANGUAGE": SignalDefinition(
        signal_code="MENTOR_COPYTRADE_LANGUAGE",
        reason_code="MENTOR_COPYTRADE_LANGUAGE",
        category=TEXTUAL_LURE,
        description="Mentor, teacher, signal group, or copy-trade lure.",
        default_weight=3.0,
        patterns=(
            r"\b(copy[- ]?trade|copy trading)\b",
            r"\btrading signals?\b",
            r"\bsignal group\b",
            r"\bteacher\b",
            r"\bmentor\b",
            r"\banalyst\b",
            r"\bprivate trading method\b",
        ),
    ),
    "PRIVATE_REDIRECT": SignalDefinition(
        signal_code="PRIVATE_REDIRECT",
        reason_code="PRIVATE_REDIRECT",
        category=REDIRECT_CONTACT,
        description="Instruction to move into private chat, group, or off-platform contact.",
        default_weight=4.0,
        patterns=(
            r"\bdm (me|for|to)\b",
            r"\bdirect message\b",
            r"\bprivate (message|group|chat)\b",
            r"\bjoin (the )?(group|channel)\b",
            r"\bmessage (me|the assistant|support)\b",
            r"\binbox me\b",
            r"\badd (me|account|line|whatsapp|telegram)\b",
            r"\btelegram\b",
            r"\bwhatsapp\b",
            r"\bline\b",
        ),
    ),
    "IMPLICIT_DM_CONTACT_REQUEST": SignalDefinition(
        signal_code="IMPLICIT_DM_CONTACT_REQUEST",
        reason_code="IMPLICIT_DM_CONTACT_REQUEST",
        category=REDIRECT_CONTACT,
        description="Private-message request that withholds the public contact route.",
        default_weight=2.5,
        patterns=(
            r"\bdm (me|for|to|get|details?)\b",
            r"\bdirect message (me|for|to|get|details?)\b",
            r"\bprivate[- ]message\b",
            r"\binbox me\b",
            r"私訊(我|貼文者|作者|版主|小編|了解|詢問|索取|領取|報名|即可|才|後)?",
            r"私我",
            r"(請|歡迎|想知道|想了解|有興趣|需要).{0,12}私訊",
            r"私訊.{0,12}(投資|賺錢|獲利|收益|群|方法|資訊|名額|機會)",
        ),
    ),
    "COMMENT_CODE_LEAD_MAGNET": SignalDefinition(
        signal_code="COMMENT_CODE_LEAD_MAGNET",
        reason_code="COMMENT_CODE_LEAD_MAGNET",
        category=REDIRECT_CONTACT,
        description="Follow/comment/code/keyword lead magnet for stock picks, lists, methods, or benefits.",
        default_weight=2.5,
        patterns=(
            r"\b(comment|reply)\s+(code|keyword)\b",
            r"\buse\s+(code|keyword)\b",
            r"\bnumeric\s+(code|keyword)\b",
            r"\b(code|keyword).{0,24}(receive|get|free|material|pick|list)\b",
            r"\bfree\s+(pick|list|guide|method|signal)\b",
            r"(追蹤|關注).{0,12}(暗號|代碼|領取|索取|免費|名單|方法|資訊)",
            r"(留言|回覆|打出|輸入).{0,12}(暗號|代碼|關鍵字)",
            r"(暗號|代碼|關鍵字).{0,12}(領取|索取|免費|名單|方法|資訊|標的)",
            r"(免費|無償).{0,12}(領取|索取).{0,12}(標的|股票|名單|方法|資訊)",
        ),
    ),
    "STOCK_PICK_PLAYBOOK_KEYWORD_FUNNEL": SignalDefinition(
        signal_code="STOCK_PICK_PLAYBOOK_KEYWORD_FUNNEL",
        reason_code="STOCK_PICK_PLAYBOOK_KEYWORD_FUNNEL",
        category=REDIRECT_CONTACT,
        description="Named short-term stock-pick lure that offers an operation script or playbook through follow/message/code action.",
        default_weight=4.0,
        patterns=(
            r"\bstock[- ]?pick playbook\b",
            r"\bnamed short[- ]?term stock[- ]?pick\b",
            r"\boperation script\b",
            r"\bcomplete operation playbook\b",
            r"\bnumeric[- ]?code action\b",
            r"\bnext (runner|winner|limit[- ]?up)\b",
            r"(下一檔|下一支).{0,16}(漲停|飆股|強勢股|強股|妖股)",
            r"(不要再錯過|錯過.{0,12}不要再錯過|閉眼進|卡位進場|破前高)",
            r"(最強短線個股|短線.{0,8}(個股|操作)|漲停基因|連板)",
            r"(追蹤|傳訊|私訊|私信).{0,12}(\\d{2,6}|代碼|暗號|關鍵字)",
            r"(完整操作劇本|操作劇本|完整劇本|買賣劇本)",
        ),
    ),
    "TRAPPED_POSITION_DM_PLAYBOOK_REPLY": SignalDefinition(
        signal_code="TRAPPED_POSITION_DM_PLAYBOOK_REPLY",
        reason_code="TRAPPED_POSITION_DM_PLAYBOOK_REPLY",
        category=REDIRECT_CONTACT,
        description="Reply-level trapped-position or loss-anxiety cue is moved into DM/private playbook guidance.",
        default_weight=4.0,
        patterns=(
            r"\btrapped[- ]?position\b",
            r"\bloss[- ]?anxiety\b",
            r"\bprivate playbook guidance\b",
            r"\bdetailed operation playbook\b",
            r"(套牢|虧損|被套|卡住).{0,24}(私訊|傳訊|私信|敲我|操作劇本|詳細)",
            r"(私訊你|傳訊你|私信你|敲你).{0,16}(操作劇本|詳細|處理|解套|劇本)",
            r"(有詳細的?操作劇本|詳細操作劇本|完整操作劇本)",
        ),
    ),
    "REPLY_IMPERSONATION_CONTACT_HIJACK": SignalDefinition(
        signal_code="REPLY_IMPERSONATION_CONTACT_HIJACK",
        reason_code="REPLY_IMPERSONATION_CONTACT_HIJACK",
        category=REDIRECT_CONTACT,
        description="Replies impersonate or appear adjacent to the poster and hijack attention into contact/group links.",
        default_weight=5.0,
        patterns=(
            r"\breply impersonation\b",
            r"\bcontact[- ]?hijack\b",
            r"\bofficially verified (line|contact|account)\b",
            r"\bofficial[- ]?contact\b",
            r"\banti[- ]?scam camouflage\b",
            r"\bother(s)? (are|is) scam(s)?\b",
            r"\bdaily lists? or holdings viewpoints?\b",
            r"\bgroup/contact paths?\b",
            r"(官方認證|本人認證|唯一).{0,16}(LINE|賴|帳號|群|群組|ID)",
            r"(其他人|收費的|其餘).{0,16}(都是|是).{0,8}詐騙",
            r"(詐騙集團|騙取|受騙).{0,24}(LINE|賴|群|帳號|ID)",
            r"(每日清單|持倉觀點|追蹤清單).{0,24}(群|群組|LINE|賴|ID)",
            r"(加LINE|加賴|搜索賴|搜尋賴|LINE[：:])",
        ),
    ),
    "CONTACT_HANDLE_PRESENT": SignalDefinition(
        signal_code="CONTACT_HANDLE_PRESENT",
        reason_code="CONTACT_HANDLE_PRESENT",
        category=REDIRECT_CONTACT,
        description="Visible contact handle, phone, email, or messaging ID.",
        default_weight=3.0,
        patterns=(
            r"@\w{3,}",
            r"\b(line|telegram|whatsapp)\s*(id|account|handle)?\b",
            r"\b\+?\d[\d\s().-]{7,}\d\b",
            r"\b[\w.+-]+@[\w.-]+\.[a-z]{2,}\b",
        ),
    ),
    "EXTERNAL_LINK_PRESENT": SignalDefinition(
        signal_code="EXTERNAL_LINK_PRESENT",
        reason_code="EXTERNAL_LINK_PRESENT",
        category=REDIRECT_CONTACT,
        description="Visible external link, shortener, or URL-like destination.",
        default_weight=1.5,
        patterns=(
            r"https?://\S+",
            r"\bwww\.\S+",
            r"\b(bit\.ly|tinyurl|t\.co|linktr\.ee|wa\.me|t\.me)/\S*",
            r"\bclick (the )?(link|bio)\b",
        ),
    ),
    "URGENCY_PRESSURE": SignalDefinition(
        signal_code="URGENCY_PRESSURE",
        reason_code="URGENCY_PRESSURE",
        category=URGENCY_PRESSURE,
        description="Scarcity, deadline, or act-now pressure.",
        default_weight=2.0,
        patterns=(
            r"\blimited (spots|seats|time|members|slots)\b",
            r"\blast chance\b",
            r"\btoday only\b",
            r"\bfew spots\b",
            r"\bfirst\s+\d+\s+(members|people|spots|users)\b",
            r"\bact now\b",
            r"\bdon'?t miss\b",
            r"\bdeadline\b",
        ),
    ),
    "TESTIMONIAL_PATTERN": SignalDefinition(
        signal_code="TESTIMONIAL_PATTERN",
        reason_code="TESTIMONIAL_PATTERN",
        category=TESTIMONIAL_SCREENSHOT,
        description="Proof, results, testimonial, or earnings screenshot pattern.",
        default_weight=2.5,
        patterns=(
            r"\btestimonial(s)?\b",
            r"\bproof\b",
            r"\bmember results\b",
            r"\bstudent success\b",
            r"\bsuccess stor(y|ies)\b",
            r"\bearnings? screenshot\b",
            r"\bprofit screenshot\b",
            r"\baccount balance\b",
            r"\bwithdrawal proof\b",
            r"\bscreenshot(s)? (are|is) in\b",
        ),
    ),
    "SCREENSHOT_EVIDENCE": SignalDefinition(
        signal_code="SCREENSHOT_EVIDENCE",
        reason_code="SCREENSHOT_EVIDENCE",
        category=TESTIMONIAL_SCREENSHOT,
        description="Screenshot-heavy item or screenshot-as-proof framing.",
        default_weight=1.0,
        patterns=(
            r"\bscreenshot(s)?\b",
            r"\bshown in the image\b",
            r"\bin the image\b",
        ),
    ),
    "PSEUDO_OFFICIAL_LANGUAGE": SignalDefinition(
        signal_code="PSEUDO_OFFICIAL_LANGUAGE",
        reason_code="PSEUDO_OFFICIAL_LANGUAGE",
        category=PSEUDO_OFFICIAL_ENDORSEMENT,
        description="Official-looking, verification, subsidy, support, or institutional framing.",
        default_weight=3.0,
        patterns=(
            r"\bofficial\b",
            r"\bverify your account\b",
            r"\bverification\b",
            r"\bsupport account\b",
            r"\breward notice\b",
            r"\bsubsidy\b",
            r"\bgrant approved\b",
            r"\bregistration page\b",
            r"\bgovernment\b",
        ),
    ),
    "CELEBRITY_ENDORSEMENT_PATTERN": SignalDefinition(
        signal_code="CELEBRITY_ENDORSEMENT_PATTERN",
        reason_code="CELEBRITY_ENDORSEMENT_PATTERN",
        category=PSEUDO_OFFICIAL_ENDORSEMENT,
        description="Celebrity, expert, news, or authority endorsement framing.",
        default_weight=2.5,
        patterns=(
            r"\bcelebrity\b",
            r"\bendorsed by\b",
            r"\bas seen on\b",
            r"\bdoctor recommended\b",
            r"\bexpert approved\b",
            r"\bnews report\b",
            r"\bfamous (investor|doctor|professor|analyst)\b",
            r"\bpublic[- ]figure\b",
            r"\bauthority[- ]hype\b",
            r"\bauthority framing\b",
        ),
    ),
    "PAYMENT_OR_CREDENTIAL_REQUEST": SignalDefinition(
        signal_code="PAYMENT_OR_CREDENTIAL_REQUEST",
        reason_code="PAYMENT_OR_CREDENTIAL_REQUEST",
        category=PAYMENT_CREDENTIAL,
        description="Payment, fee, wallet, credential, bank, identity, or verification ask.",
        default_weight=5.0,
        patterns=(
            r"\bdeposit\b",
            r"\b(release|shipping|verification)\s+fee\b",
            r"\bwallet transfer\b",
            r"\bcredit card\b",
            r"\blogin\b",
            r"\bpassword\b",
            r"\bbank (info|account|details)\b",
            r"\bpersonal information\b",
            r"\bid number\b",
            r"\bpay (a|the|small)\b",
        ),
    ),
    "OCR_SUSPICIOUS_TEXT": SignalDefinition(
        signal_code="OCR_SUSPICIOUS_TEXT",
        reason_code="OCR_SUSPICIOUS_TEXT",
        category=OCR_CONTEXT,
        description="Suspicious signal appears in OCR text from image or screenshot evidence.",
        default_weight=1.0,
        patterns=(),
    ),
    "REPLY_FUNNEL_PATTERN": SignalDefinition(
        signal_code="REPLY_FUNNEL_PATTERN",
        reason_code="REPLY_FUNNEL_PATTERN",
        category=REPLY_FUNNEL,
        description="Suspicious funneling signal appears in replies/comments.",
        default_weight=1.5,
        patterns=(),
    ),
}


REASON_CODE_ORDER = [
    "PAYMENT_OR_CREDENTIAL_REQUEST",
    "GUARANTEED_PROFIT",
    "LOW_EFFORT_HIGH_RETURN",
    "PAST_PERFORMANCE_PROFIT_PROOF",
    "HIGH_FEE_COURSE_FUNNEL",
    "STOCK_RESCUE_GROUP_FUNNEL",
    "INDIVIDUAL_STOCK_ADVICE_REPLY_FUNNEL",
    "MARKET_DIRECTION_HERDING_CHORUS",
    "INSTITUTIONAL_FLOW_AUTHORITY_LURE",
    "LIFESTYLE_TRUST_MARKET_REASSURANCE_FUNNEL",
    "BEGINNER_EASY_MONEY",
    "MENTOR_COPYTRADE_LANGUAGE",
    "PRIVATE_REDIRECT",
    "IMPLICIT_DM_CONTACT_REQUEST",
    "COMMENT_CODE_LEAD_MAGNET",
    "STOCK_PICK_PLAYBOOK_KEYWORD_FUNNEL",
    "TRAPPED_POSITION_DM_PLAYBOOK_REPLY",
    "DARK_HORSE_STOCK_TARGET_PRICE_DM_FUNNEL",
    "CODED_ANIMAL_STOCK_LIMIT_UP_GROUP_FUNNEL",
    "MASS_STOCK_COMMAND_LIST_GROUP_FUNNEL",
    "TRADING_RULES_WEALTH_AUTHORITY_FOLLOW_GATE",
    "BRAND_PATENT_EXTREME_ROI_CONTACT_FUNNEL",
    "REPLY_IMPERSONATION_CONTACT_HIJACK",
    "CONTACT_HANDLE_PRESENT",
    "EXTERNAL_LINK_PRESENT",
    "URGENCY_PRESSURE",
    "TESTIMONIAL_PATTERN",
    "SCREENSHOT_EVIDENCE",
    "PSEUDO_OFFICIAL_LANGUAGE",
    "CELEBRITY_ENDORSEMENT_PATTERN",
    "OCR_SUSPICIOUS_TEXT",
    "REPLY_FUNNEL_PATTERN",
    "MULTI_SIGNAL_CONVERGENCE",
]


FIELD_LABELS = {
    "post_text": "post text",
    "reply_texts": "replies",
    "ocr_text": "OCR text",
    "external_links": "external link fields",
    "visible_contact_handles": "visible contact handles",
    "visible_platform_redirects": "visible platform redirects",
    "screenshot_style": "screenshot style field",
}
