#!/usr/bin/env python3
"""Initialize local-only working files for the first Threads pilot.

This script does not collect Threads data. It only creates empty local files
from committed templates after the project owner has confirmed that controlled
launch details exist outside git.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import shutil
import sys


DEFAULT_DATASET_ID = "threads_pilot_v1_2026-05"
DEFAULT_BATCH_ID = "threads_pilot_v1_2026-05"


@dataclass(frozen=True)
class TemplateCopy:
    source: Path
    target_name: str
    description: str


TEMPLATE_COPIES = (
    TemplateCopy(
        Path("templates/collection_log_template.csv"),
        "threads_pilot_v1_collection_log.csv",
        "collection log",
    ),
    TemplateCopy(
        Path("templates/annotation_sheet_template.csv"),
        "threads_pilot_v1_annotations.csv",
        "primary annotation sheet",
    ),
    TemplateCopy(
        Path("templates/annotation_sheet_template.csv"),
        "threads_pilot_v1_annotation_pass_ann_01.csv",
        "annotator 1 pass",
    ),
    TemplateCopy(
        Path("templates/annotation_sheet_template.csv"),
        "threads_pilot_v1_annotation_pass_ann_02.csv",
        "annotator 2 pass",
    ),
    TemplateCopy(
        Path("templates/pilot_checkpoint_review.md"),
        "threads_pilot_v1_checkpoint_review.md",
        "first checkpoint review worksheet",
    ),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create empty local-only pilot files under ignored data/interim/. "
            "Run only after controlled launch details are recorded outside git."
        )
    )
    parser.add_argument(
        "--dataset-id",
        default=DEFAULT_DATASET_ID,
        help=f"Dataset ID to write into generated local markdown files. Default: {DEFAULT_DATASET_ID}",
    )
    parser.add_argument(
        "--batch-id",
        default=DEFAULT_BATCH_ID,
        help=f"Collection batch ID to write into generated local markdown files. Default: {DEFAULT_BATCH_ID}",
    )
    parser.add_argument(
        "--output-dir",
        default="data/interim",
        type=Path,
        help="Ignored local workspace directory. Default: data/interim",
    )
    parser.add_argument(
        "--ack-controlled-details",
        action="store_true",
        help=(
            "Acknowledge that exact source, storage, access, retention, and "
            "redaction limits are recorded in the controlled non-git location."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing local files. Use only after confirming they contain no needed work.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show the files that would be created without writing anything.",
    )
    return parser.parse_args()


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def render_markdown_template(text: str, dataset_id: str, batch_id: str) -> str:
    text = text.replace(f"| Dataset ID | `{DEFAULT_DATASET_ID}` |", f"| Dataset ID | `{dataset_id}` |")
    text = text.replace(f"| Collection batch ID | `{DEFAULT_BATCH_ID}` |", f"| Collection batch ID | `{batch_id}` |")
    return text


def build_manifest(dataset_id: str, batch_id: str, targets: list[Path]) -> str:
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    target_list = "\n".join(f"- `{path.as_posix()}`" for path in targets)
    return f"""# Local Pilot Workspace Manifest

Generated by `scripts/init_pilot_workspace.py`.

## Identity

| Field | Value |
|---|---|
| Dataset ID | `{dataset_id}` |
| Collection batch ID | `{batch_id}` |
| Generated at UTC | `{generated_at}` |

## Local Files

{target_list}

## Safety Notes

- These files are local working files and are ignored by git.
- Do not commit raw Threads content, screenshots, personal data, source URLs, handles, credentials, browser exports, or stakeholder case packets.
- Keep raw evidence outside git in the approved controlled storage location.
- Fill these files only according to the controlled launch record.
- Pause after the first 10-15 collected or annotated items and run the first checkpoint.
"""


def copy_template(
    root: Path,
    entry: TemplateCopy,
    target: Path,
    dataset_id: str,
    batch_id: str,
) -> None:
    source = root / entry.source
    if entry.source.suffix == ".md":
        text = source.read_text(encoding="utf-8")
        target.write_text(render_markdown_template(text, dataset_id, batch_id), encoding="utf-8")
    else:
        shutil.copyfile(source, target)


def main() -> int:
    args = parse_args()
    root = repo_root()
    output_dir = args.output_dir
    if not output_dir.is_absolute():
        output_dir = root / output_dir

    planned_targets = [output_dir / entry.target_name for entry in TEMPLATE_COPIES]
    manifest_target = output_dir / "threads_pilot_v1_workspace_manifest.md"
    all_targets = [*planned_targets, manifest_target]

    print("Threads pilot local workspace initializer")
    print("")
    print("This script creates empty local working files only. It does not collect data.")
    print("Use it only after controlled launch details are complete outside git.")
    print("")

    if not args.dry_run and not args.ack_controlled_details:
        print(
            "ERROR: refusing to write files without --ack-controlled-details.\n"
            "Complete the controlled launch record first, then rerun with the acknowledgement.",
            file=sys.stderr,
        )
        return 2

    missing_sources = [root / entry.source for entry in TEMPLATE_COPIES if not (root / entry.source).exists()]
    if missing_sources:
        print("ERROR: missing template files:", file=sys.stderr)
        for source in missing_sources:
            print(f"- {source}", file=sys.stderr)
        return 1

    existing_targets = [target for target in all_targets if target.exists()]
    if existing_targets and not args.force:
        print("ERROR: target files already exist. Rerun with --force only if overwriting is intended.", file=sys.stderr)
        for target in existing_targets:
            print(f"- {target}", file=sys.stderr)
        return 1

    if args.dry_run:
        print("Dry run: no files will be written.")
        for entry, target in zip(TEMPLATE_COPIES, planned_targets):
            print(f"would create {entry.description}: {target}")
        print(f"would create workspace manifest: {manifest_target}")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    for entry, target in zip(TEMPLATE_COPIES, planned_targets):
        copy_template(root, entry, target, args.dataset_id, args.batch_id)
        print(f"created {entry.description}: {target}")

    manifest_target.write_text(build_manifest(args.dataset_id, args.batch_id, all_targets), encoding="utf-8")
    print(f"created workspace manifest: {manifest_target}")
    print("")
    print("Next: fill collection rows only under the controlled launch limits, then run the 10-15 item checkpoint.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
